package ai.attus.gerenciamento_contratos;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class GerenciamentoContratosApplicationTests {

	@Test
	void contextLoads() {
		// This method is typically used to verify that the Spring application context is
		// loaded correctly. This test method is automatically generated by the Spring Boot
		// testing framework when creating the project.
	}

}
